# This workflow will run all checks required for a PR to be merged.

name: Build and Test ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check Yarn Version
        run: yarn --version

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Check linting and formatting
        run: |
          if yarn lint && yarn format:check; then
            echo "Linting and formatting checks passed."
          else
            echo "Linting or formatting checks failed. Please fix the issues."
            exit 1
          fi

      - name: Build Puck
        run: |
          yarn build --scope @measured/puck --no-deps

      - name: Build recipe/next
        run: |
          yarn build --scope next-recipe --no-deps

      - name: Build recipe/remix
        run: |
          yarn build --scope remix-recipe --no-deps

      - name: Check for build failures
        run: |
          if [ $? -ne 0 ]; then
            echo "Build failed. Please fix the issues."
            exit 1
          fi
